import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import currentImage from "../assets/TAT.jpg";


export default function Test(props: {
  headerText?: string;
  image?: any;
  gridboxes?: any[];
}) {
  const {
    headerText = <span>What are the people in this image <span className="emphasis">thinking</span> and <span className="emphasis">feeling</span>?</span>,
    image = <Image src={currentImage} />,
    gridboxes = [
      {
        isTyping: false,
        text: 'Submit your answer ',
        emoji: <span className="option-icon">&rarr;</span>
      },
      {
        isTyping: false,
        text: "Choose a different image...",
        emoji: <span className="option-icon">&lArr;</span>
      },
    ],
  } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>TAT test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1 className={styles.title}>{headerText}</h1>

        <div className={styles.description}>{image}</div>

        
      </main>

      <footer className={styles.footer}>
        <div className={styles.grid}>
            {gridboxes.map((box, i) => {
              return (
                <a key={i} href="https://nextjs.org/docs" className={styles.card}>
                  <h2>{box.text} {box.emoji}</h2>
                </a>
              );
            })}
          </div>
      </footer>
    </div>
  );
}

const Header = () => {
  return (
    <header className="navheader">
        <pre className="addr">#0xDC25EF3F5B8</pre> there are <pre>3</pre> other testers
    </header>
  )
}
